### PR TITLE
open source tool semgrep

### PR DESCRIPTION
**Pull request by wurstbrot**
I am evaluting semgrep vs. sonarqube. No result yet, but maybe it is worth to mention one open source tool

### CODE REVIEW

**Comment by bob5ec** [comment]
Let's put this on hold, till you have positive results.

**Comment by mvollmary** [comment]
@wurstbrot any updates on your evaluation?

**Comment by wurstbrot** [comment]
In the end, we ended up with eslint, as it is used by developers, already.
https://eslint.org/
https://www.npmjs.com/package/eslint-plugin-angularjs-security-rules.

**Comment by mvollmary** [comment]
Thanks a lot for your input. We will add ESLint in this activity.

I will close this PR, I created a new one for ESLint.

**Pull request closed without merging**
